config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :patients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ActiveRecord::Base
    def self.search(search)
        where("lastname LIKE ?", "#{search}%")
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
    if params[:search]
      @patients = Patient.search(params[:search]).order("created_at DESC")
    else
      @patients = Patient.all.order('created_at DESC')
  end
end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:firstname, :lastname, :dateofbirth, :address, :phonenumber, :infection, :injury, :observations)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hospitaldb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="index.html">Start Bootstrap</a>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="nav" id="nav">
        <li>
          <%= render 'devise/menu/registration_items' %>
        </li>
        <li>
          <%= render 'devise/menu/login_items' %>
        </li>
        <li class="search-bar">
          <%= form_tag(patients_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Patients By Lastname" %>
          <%= submit_tag "Search" %>
        </li>
      </ul>
      
<% end %>
      
    </div>
  </nav>
    
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <nav role="navigation">
      <div class="inner">
        <a href="#nav" class="nav-collapse" id="nav-collapse">Menu</a>
      </div>
</nav>
</div>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname, id: :patient_firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname, id: :patient_lastname %>
  </div>

  <div class="field">
    <%= form.label :dateofbirth %>
    <%= form.text_field :dateofbirth, id: :patient_dateofbirth %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :patient_address %>
  </div>

  <div class="field">
    <%= form.label :phonenumber %>
    <%= form.number_field :phonenumber, id: :patient_phonenumber %>
  </div>

  <div class="field">
    <%= form.label :infection %>
    <%= form.text_field :infection, id: :patient_infection %>
  </div>

  <div class="field">
    <%= form.label :injury %>
    <%= form.text_field :injury, id: :patient_injury %>
  </div>

  <div class="field">
    <%= form.label :observations %>
    <%= form.text_field :observations, id: :patient_observations %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<br>
<br>

<h1>Patients</h1>

<table class ="table">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Dateofbirth</th>
      <th>Address</th>
      <th>Phonenumber</th>
      <th>Infection</th>
      <th>Injury</th>
      <th>Observations</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.firstname %></td>
        <td><%= patient.lastname %></td>
        <td><%= patient.dateofbirth %></td>
        <td><%= patient.address %></td>
        <td><%= patient.phonenumber %></td>
        <td><%= patient.infection %></td>
        <td><%= patient.injury %></td>
        <td><%= patient.observations %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @patient.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @patient.lastname %>
</p>

<p>
  <strong>Dateofbirth:</strong>
  <%= @patient.dateofbirth %>
</p>

<p>
  <strong>Address:</strong>
  <%= @patient.address %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @patient.phonenumber %>
</p>

<p>
  <strong>Infection:</strong>
  <%= @patient.infection %>
</p>

<p>
  <strong>Injury:</strong>
  <%= @patient.injury %>
</p>

<p>
  <strong>Observations:</strong>
  <%= @patient.observations %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>